name: Test

on:
  push:
    branches:
      - main
      - master
      - develop
    paths-ignore:
      - '**.md'
      - '**.env*'
  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - '**.md'
      - '**.env*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        ports:
          - 33061:3306
        env:
          MYSQL_DATABASE: example
          MYSQL_ROOT_USER: root
          MYSQL_ROOT_PASSWORD: password
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Check out code
        uses: actions/checkout@v2

      - name: Cache go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Run go fmt
        if: runner.os != 'Windows'
        run: diff -u <(echo -n) <(gofmt -d -s .)
      - name: Run go vet
        run: go vet ./...

      - name: Run go test
        run: |
          go test -v ./...
        env:
          PORT: 8080
          MAX_OPEN_CONNS: 30
          MAX_IDLE_CONNS: 30
          MYSQL_DATABASE: example
          MYSQL_DSN: root:password@tcp(localhost:33061)/example?charset=utf8mb4&parseTime=True
          ALLOW_CORS_ORIGIN: "*"
